const DISTRIBUTORS = [
  "Adidas",
  "ASOS",
  "City Gear",
  "Crocs",
  "Ebay",
  "Joes New Balance",
  "Hibbett Sports",
  "Snipes",
  "Shop Simon",
  "Shoe Palace",
  "SSENSE",
  "Finishline",
  "Hoka",
  "On",
  "Nike",
  "Macys",
  "Kohls",
  "Net A Porter",
  "Mr. Porter",
  "Orleans Shoe Co",
  "Revolve",
  "Zappos",
  "gorjana",
  "Best Buy",
  "Kith",
  "New Balance Athletics, Inc.",
  "ShopSimon",
  "Shop WSS",
  "Oneness Boutique",
];

export default DISTRIBUTORS;
